views:
  default:
    sort:
      by: timestamp   # or "none" to keep original order
      order: asc      # "asc" or "desc"
    # 0 or missing = unlimited
    max_events_per_detection: 0
    per_source:
      ssh:
        show_fields:
          - timestamp
          - host
          - user
          - ip
          - status
      sudo:
        show_fields:
          - timestamp
          - host
          - user
          - target_user
          - command

  compact:
    sort:
      by: timestamp
      order: desc
    max_events_per_detection: 5
    per_source:
      ssh:
        show_fields:
          - timestamp
          - user
          - ip
      sudo:
        show_fields:
          - timestamp
          - user
          - command

